# Generated by Django 2.0.2 on 2018-09-24 03:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User_get_API', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='User_Profile',
        ),
    ]
