# Generated by Django 2.0.2 on 2018-09-24 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User_get_API', '0002_auto_20180924_0916'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_profile',
            name='Address',
            field=models.CharField(default=False, max_length=30),
        ),
        migrations.AddField(
            model_name='user_profile',
            name='City',
            field=models.CharField(default=False, max_length=10),
        ),
        migrations.AddField(
            model_name='user_profile',
            name='Education',
            field=models.CharField(default=False, max_length=10),
        ),
        migrations.AddField(
            model_name='user_profile',
            name='Fathers_Name',
            field=models.CharField(default=False, max_length=20),
        ),
        migrations.AddField(
            model_name='user_profile',
            name='First_Name',
            field=models.CharField(default=False, max_length=10),
        ),
        migrations.AddField(
            model_name='user_profile',
            name='Last_Name',
            field=models.CharField(default=False, max_length=10),
        ),
        migrations.AddField(
            model_name='user_profile',
            name='Mothers_Name',
            field=models.CharField(default=False, max_length=20),
        ),
        migrations.AddField(
            model_name='user_profile',
            name='Phone_No',
            field=models.IntegerField(default=False),
        ),
        migrations.AddField(
            model_name='user_profile',
            name='Pin_Code',
            field=models.IntegerField(default=False),
        ),
        migrations.AlterField(
            model_name='user_profile',
            name='Name',
            field=models.CharField(default=False, max_length=20),
        ),
    ]
